baseURL = 'https://kyettran.site/'
languageCode = 'en-us'
title = 'Kyet Tran'
theme = 'PaperMod'

[pagination]
  pagerSize = 5

[params]
  author = "Kyet Tran"
  description = "DevOps | Backend | Linux"
  defaultTheme = "dark"

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

  ShowToc = false

  [params.homeInfoParams]
    Title = "Hi, I'm Kyet 👋"
    Content = """
DevOps Learner 🚀  
Linux • Docker • Nginx • CI/CD  
Building things step by step.
"""

[[params.socialIcons]]
name = "github"
url = "https://github.com/kyettran"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/trankiet317/"

[params.profileMode]
enabled = true
title = "Kyet Tran"
subtitle = "I'm System Engineer - DevOps Learner 🚀"
imageUrl = "images/avatar.jpeg"
imageWidth = 150
imageHeight = 150
imageTitle = "Kyet Tran"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10
