baseURL = "https://kyettran.site/"
languageCode = "en-us"
title = "Kyet Tran | System Engineer"
theme = "PaperMod"

[pagination]
  pagerSize = 5

[params]
  author = "Kyet Tran"
  description = "System Engineer | DevOps Learner | Linux • Docker • CI/CD"
  keywords = ["DevOps", "Linux", "Docker", "Nginx", "CI/CD"]
  defaultTheme = "dark"
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowToc = false

  displayFullLangName = true

# Homepage profile mode
[params.profileMode]
enabled = true
title = "Kyet Tran"
subtitle = "I'm a System Engineer & DevOps Learner 🚀"
imageUrl = "images/avatar.jpeg"
imageWidth = 160
imageHeight = 160
imageTitle = "Kyet Tran"

buttons = [
  { name = "Blog", url = "/posts" },
  { name = "About Me", url = "/about" }
]

# Social Links
[[params.socialIcons]]
name = "github"
url = "https://github.com/kyettran"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/trankiet317/"

# Menu
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "posts"
name = "Blog"
url = "/posts/"
weight = 20
